import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "~/components/navigation";
import { cn } from "~/lib/utils";
import { Providers } from "./providers";
import { Analytics } from '@vercel/analytics/react';


const mono = JetBrains_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <Providers>
      <body className={cn(mono.className, "mt-12")}>
        <Navbar />
        {children}
        <Analytics />
        </body>
        </Providers>
    </html>
  );
}
